export const ITEM_CREATED = 'ITEM_CREATED';
export const ITEM_CHECKED = 'ITEM_CHECKED';
export const ITEM_UNCHECKED = 'ITEM_UNCHECKED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_RENAMED = 'ITEM_RENAMED';
