export const ITEM_CREATED = 'ITEM_CREATED';
export const ITEM_CHECKED = 'ITEM_CHECKED';
export const ITEM_UNCHECKED = 'ITEM_UNCHECKED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_RENAMED = 'ITEM_RENAMED';
export const LIST_SAVED = 'LIST_SAVED';
export const LOCAL_STORAGE_LIST_RETREIVED = 'LOCAL_STORAGE_LIST_RETREIVED';
